### ISSUE TITLE
unrecognized option: S for BusyBox's env in index.ts shabang

### ISSUE THREAD

**Issue by tofran** [dstoyanoff/directus-auto-migrate#9]
As of right now `index.ts` has the following shabang:
https://github.com/dstoyanoff/directus-auto-migrate/blob/db50e821464d9eef4398b02cfd5afef7d242bd49/src/index.ts#L1

It was added in c4bbbf32a2e2d61235fd4f91c8fa8cb105e19b07.

But unfortunately BusyBox's env does not have -S option, furthermore directus official docker image is based on BusyBox (as it is based on [node:16-alpine](https://github.com/nodejs/docker-node/blob/fa12fbdebdc5881ede3991184d81793b768caf3a/16/alpine3.15/Dockerfile)).

```
# env --help
BusyBox v1.34.1 (2022-04-04 10:19:27 UTC) multi-call binary.

Usage: env [-i0] [-u NAME]... [-] [NAME=VALUE]... [PROG ARGS]

Print current environment or run PROG after setting up environment

        -, -i   Start with empty environment
        -0      NUL terminated output
        -u NAME Remove variable from environment
```

---

**How to reproduce:**

1. Run `directus/directus:latest` docker image.
2. Exec `npx directus-auto-migrate my-first-migration` inside the container.
   
    ```
    # npx directus-auto-migrate my-first-migration
    Need to install the following packages:
      directus-auto-migrate
    Ok to proceed? (y) y
    /usr/bin/env: unrecognized option: S
    BusyBox v1.34.1 (2022-04-04 10:19:27 UTC) multi-call binary.
    
    Usage: env [-i0] [-u NAME]... [-] [NAME=VALUE]... [PROG ARGS]
    
    Print current environment or run PROG after setting up environment
    
            -, -i   Start with empty environment
            -0      NUL terminated output
            -u NAME Remove variable from environment
    ```

---

Why do we need this shabang? Why do we need typescript (`ts-node`) in the final build (`index.js`)?

Why doesn't directus-auto-migrate read from env vars (only `.env` file)? Should I create a different issue for this one?

**Comment by dstoyanoff** [comment]
Hello,
Is there a reason to still use this package? I have stopped maintaining it since directus released their built-in schema snapshots functionality, which is influenced by this project, but adapted more on their own preferences. I would suggest going there first. If you insist to use this package, PR's are welcome, but I am not planning to invest time in testing the changes myself.

**Comment by piotr-cz** [comment]
Might be related: https://github.com/dstoyanoff/directus-auto-migrate/issues/7

@dstoyanoff
If this package is not actively maintained because similar functionality is available with Directus CLI, please update the README.md.
I just started working with Directus and I'm not aware yet of what's included and what is not.
